# Generated by Django 3.0 on 2023-03-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
    ]

    operations = [
    ]
