# Generated by Django 3.0 on 2023-04-05 14:37

from django.db import migrations


class Migration(migrations.Migration):
    run_before = [
        ("oc_lettings_site", "0002_auto_20230328_1354"),
        ("lettings", "0002_auto_20230328_1358"),
        ("profiles", "0002_auto_20230329_1735")
    ]

    operations = [
        migrations.RemoveField(
            model_name="letting",
            name="address",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Letting",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
